import pandas as pd

from scripts.derive import threshold_agreement
from scripts.io import ROOT, load_config, read_csv


def _table(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for r in df.itertuples(index=False):
        lines.append("| " + " | ".join("" if pd.isna(v) else str(v) for v in r) + " |")
    return "\n".join(lines)


def _pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def build_report() -> str:
    cfg = load_config()
    answers = read_csv("data/interim/answers.csv")
    cits = read_csv("data/interim/citations.csv")
    sents = read_csv("data/interim/sentences.csv")
    ments = read_csv("data/interim/mentions.csv")
    pages = read_csv("data/interim/pages.csv")
    scores = read_csv("data/interim/attribution_scores.csv")
    check = read_csv("data/labels/attribution_check.csv")
    hits = read_csv("data/labels/ambiguous_hits.csv")
    spot = read_csv("data/labels/sentiment_spotcheck.csv")
    readable = pages.is_readable.astype(str) == "True"
    exp = cfg["expected_counts"]
    out = ["# Data quality report", "",
           "Generated by `python -m scripts.quality` from the files in `data/`. Rerun it after any data change.", "",
           f"Run date of all answers: {cfg['run_date']}. Engines: ChatGPT and Gemini, 20 prompts each.", ""]

    out += ["## Counts", "", _table(pd.DataFrame([
        ("Answers", exp["answers"], len(answers)),
        ("Citations (links under the source heading, deduplicated within an answer)", exp["citations"], len(cits)),
        ("Unique cited URLs", exp["unique_urls"], cits.url.nunique()),
        ("Unique cited domains", exp["domains"], cits.domain.nunique()),
        ("Answer sentences", "", len(sents)),
        ("Brand mentions (parent brand credited)", "", len(ments)),
        ("Brands mentioned", "", ments.brand.nunique()),
    ], columns=["Item", "Expected", "Actual"])), ""]

    per = cits.groupby("answer_id").size()
    odd = per[per != 10]
    out += ["## Citations per answer", "",
            f"{int((per == 10).sum())} of {len(per)} answers list exactly 10 sources."]
    for aid, n in odd.items():
        out.append(f"- `{aid}` has {n}: the same page appears twice in its list (once with a trailing slash), so it is counted once.")
    out += ["", "Data fixes made before analysis:",
            "- ChatGPT prompt 8: the first copy had no source list (product cards only). RG re-ran it on 2026-10-09; the re-run replaces the whole answer.",
            "- ChatGPT prompt 9: the sheet held a prompt 8 answer by mistake. RG re-ran prompt 9; the re-run replaces the whole answer.",
            ""]

    p = pages.copy()
    p["status"] = p.http_status.map(lambda v: "" if pd.isna(v) else str(int(float(v))))

    def reason(r):
        if str(r.is_readable) == "True":
            return "readable"
        if str(r.get("soft_404", "")) == "True":
            return "soft 404 (error page with status 200)"
        if isinstance(r.fetch_error, str) and r.fetch_error:
            return r.fetch_error.split(":")[0]
        if r.status and r.status != "200":
            return f"HTTP {r.status}"
        return f"fewer than {cfg['readable_min_words']} words of text"

    p["reason"] = p.apply(reason, axis=1)
    cr = cits.merge(p[["url", "reason"]], on="url")
    out += ["## Crawl outcomes", "",
            f"{int(readable.sum())} of {len(p)} unique pages were readable ({_pct(readable.mean())}). "
            f"They cover {_pct((cr.reason == 'readable').mean())} of all citations.", "",
            _table(p.reason.value_counts().rename_axis("Outcome").reset_index(name="Pages")), "",
            "Every unreadable page:", "",
            _table(p[~readable][["url", "reason"]].rename(columns={"url": "URL", "reason": "Reason"})), ""]

    t0 = cfg["attribution_threshold"]
    scan = pd.DataFrame([(t, threshold_agreement(scores, check, t)) for t in
                         [0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50]], columns=["Threshold", "Agreement (of 30)"])
    agree = threshold_agreement(scores, check, t0)
    att = scores[(scores.best_score >= t0) & scores.best_url.isin(set(p[readable].url))]
    cov = att.merge(answers[["answer_id", "engine"]], on="answer_id").groupby("engine").size() / \
        sents.merge(answers[["answer_id", "engine"]], on="answer_id").groupby("engine").size()
    out += ["## Attribution check", "",
            "Source PAWC needs to know which cited page each answer sentence came from. Neither engine marks this, "
            "so the pipeline matches each sentence to the cited page that shares the most word pairs with it.", "",
            f"To check the matching, Claude labelled 30 sentences by hand (15 per engine, fixed random seed) before "
            f"looking at the scores, using page titles and URLs. At the chosen threshold of {t0:.2f} the automatic match "
            f"agrees on {agree} of 30. The target was {cfg['attribution_min_agreement']}, so the target was not met.", "",
            _table(scan), "",
            "Most disagreements are claims that appear on several cited pages (for example the Rp2 billion LPS limit appears "
            "on lps.go.id, a BTN article, detik and zaipad). The matcher finds a page that contains the claim, which is not "
            "always the page a person would pick. Read Source PAWC as the share of an answer found in each cited page, "
            "not as proof of where the engine took it from.", "",
            "Share of sentences matched to a readable cited page:", "",
            _table(cov.rename("Coverage").map(_pct).rename_axis("Engine").reset_index()), ""]

    out += ["## Ambiguous brand hits", "",
            "Aliases that are also ordinary words were reviewed one by one in context. Lowercase \"jago\" is never "
            "counted because the alias is case-sensitive.", "",
            _table(hits.groupby(["alias", "decision"]).size().rename("Hits").reset_index()), ""]

    out += ["## Sentiment spot-check", "",
            "Claude labelled sentiment for every answer and bank pair. RG was asked to check 4 answers picked at random.", "",
            _table(spot), ""]

    out += ["## Known limitations", "",
            "- One run per prompt per engine, from RG's accounts on 2026-10-09. AI answers vary between runs, so this is a snapshot.",
            "- Every prompt asked for 10 sources, which pushes both engines to cite more than they would by default.",
            "- Source PAWC uses reconstructed attribution (word-pair overlap), not attribution the engines published. See the check above.",
            "- Pages that blocked the crawler or returned too little text cannot count toward Source PAWC or Source-SOV.",
            "- Source-SOV gives each page equal weight. The raw mention count version is kept as `source_sov_raw`.",
            "- Brand counts in crawled pages skip bare ambiguous aliases (for example \"Jago\" without \"Bank\"), which undercounts some digital banks in sources.",
            "- Sentiment and domain types were labelled by Claude. The spot-check result is shown above.",
            "- Mobile apps and subsidiaries credit their parent bank (blu, myBCA and BCA mobile count for BCA).", ""]
    return "\n".join(out)


def main() -> None:
    (ROOT / "docs/data-quality.md").write_text(build_report(), encoding="utf-8")


if __name__ == "__main__":
    main()
